In [3]:
import spacy
from spacy.matcher import PhraseMatcher
import pandas as pd

In [4]:
# Load a spaCy language model (Portuguese in this case)
# python -m spacy download pt_core_news_lg
try:
    nlp = spacy.load("pt_core_news_lg")
    print("Loaded pt_core_news_lg model.")
except OSError:
    print("Model 'pt_core_news_lg' not found. Trying 'pt_core_news_sm'.")
    print("Install larger model with: python -m spacy download pt_core_news_lg")

Loaded pt_core_news_lg model.

In [5]:
# 1. Define skills list
skill_list = ['a/b testing', 'adaptabilidade', 'ai', 'airflow', 'análise de dados', 'análise de negócios', 'api', 'aprendizado de máquina', 
              'aprendizado por reforço', 'arquitetura de dados', 'artificial intelligence', 'aws', 'azure', 'bi', 'big data', 
              'business analytics', 'business intelligence', 'ciência de dados', 'cloud', 'cloud computing', 'colaboração', 
              'computação em nuvem', 'computer vision', 'comunicação eficaz', 'critical thinking', 'data analysis', 'data architecture', 
              'data cleaning', 'data engineering', 'data governance', 'data mining', 'data pipeline', 'data quality', 'data science', 
              'data storytelling', 'data visualization', 'data warehouse', 'data wrangling', 'deep learning', 'docker', 
              'engenharia de dados', 'estatística', 'etl', 'excel', 'feature engineering', 'gcp', 'governança de dados', 'hadoop', 'ia', 
              'inteligência artificial', 'inteligência de negócios', 'kubernetes', 'limpeza de dados', 'machine learning', 'matlab', 
              'mineração de dados', 'mysql', 'natural language processing', 'nlp', 'nosql', 'numpy', 'nuvem', 'pandas', 
              'pensamento crítico', 'pipelines', 'pln', 'postgresql', 'power bi', 'predictive', 'preditiva', 'problem solving', 
              'processamento de linguagem natural', 'python', 'pytorch', 'qualidade dos dados', 'r', 'redes neurais', 
              'reinforcement learning', 'scikit-learn', 'solução de problemas', 'spark', 'sql', 'sql server', 'stata', 'statistics', 
              'séries temporais', 'tableau', 'tensorflow', 'testes a/b', 'time series', 'trabalho em equipe', 'visualização de dados', 
              'visão computacional', 'programação']

# skill_list = [x.lower() for x in skill_list]
skill_list = list(set(skill_list))

In [32]:
skill_list

['machine learning',
 'cloud computing',
 'artificial intelligence',
 'cloud',
 'visão computacional',
 'data warehouse',
 'tensorflow',
 'feature engineering',
 'programação',
 'kubernetes',
 'data visualization',
 'pln',
 'pipelines',
 'governança de dados',
 'gcp',
 'excel',
 'tableau',
 'adaptabilidade',
 'computer vision',
 'pensamento crítico',
 'azure',
 'computação em nuvem',
 'estatística',
 'ai',
 'r',
 'trabalho em equipe',
 'hadoop',
 'limpeza de dados',
 'arquitetura de dados',
 'data cleaning',
 'séries temporais',
 'postgresql',
 'business intelligence',
 'time series',
 'python',
 'data architecture',
 'a/b testing',
 'etl',
 'inteligência de negócios',
 'ciência de dados',
 'reinforcement learning',
 'natural language processing',
 'problem solving',
 'inteligência artificial',
 'colaboração',
 'aprendizado por reforço',
 'data wrangling',
 'engenharia de dados',
 'redes neurais',
 'airflow',
 'nosql',
 'data analysis',
 'data quality',
 'comunicação eficaz',
 'aprendizado de máquina',
 'pytorch',
 'mysql',
 'data pipeline',
 'nlp',
 'business analytics',
 'data engineering',
 'preditiva',
 'data science',
 'deep learning',
 'solução de problemas',
 'critical thinking',
 'nuvem',
 'big data',
 'data storytelling',
 'mineração de dados',
 'statistics',
 'stata',
 'sql',
 'data governance',
 'power bi',
 'data mining',
 'ia',
 'spark',
 'testes a/b',
 'análise de negócios',
 'api',
 'scikit-learn',
 'bi',
 'análise de dados',
 'predictive',
 'pandas',
 'docker',
 'visualização de dados',
 'aws',
 'processamento de linguagem natural',
 'matlab',
 'sql server',
 'numpy',
 'qualidade dos dados']

In [6]:
# 2. Prepare the Matcher
matcher = PhraseMatcher(nlp.vocab, attr="LOWER") # Match case-insensitively

# Convert skill strings to spaCy Doc objects for PhraseMatcher
skill_patterns = [nlp.make_doc(text) for text in skill_list]
matcher.add("SKILL", skill_patterns) # Add the patterns to the matcher

In [ ]:
df = pd.read_csv('../data/raw/jobs_data.csv')


tqdm.pandas(desc="Extracting skills")
df["skills_found"] = df['text_column'].progress_apply(self.extract_skills)
df

NameError: name 'text_column' is not defined

In [36]:
# 3. Your Sample Job Description
job_descriptions = pd.read_csv('../data/raw/jobs_data.csv')['job_description']

job_descriptions.head()

0    Dandy is transforming the massive ($200B) but ...
1    Onebridge is a Consulting firm with an HQ in I...
2    HCLTech is a global technology company, spread...
3    About CloudWalk:\nWe are not just another fint...
4    We’re growing! Don't miss the opportunity to b...
Name: job_description, dtype: object

In [9]:
doc = nlp('estatística')
matches = matcher(doc)
matches

[(246859891514552380, 0, 1)]

In [9]:
# 4. Process the Text and Find Matches
for job_description_text in job_descriptions[:20]:
    doc = nlp(job_description_text)
    matches = matcher(doc)

    # Extract the matched skill texts, ensuring uniqueness
    found_skills = set()
    for match_id, start, end in matches:
        span = doc[start:end]  # The matched span
        found_skills.add(span.text.strip()) # Use text and add to set to avoid duplicates

    if found_skills:
        for skill in sorted(list(found_skills)): # Sort for consistent output
            print(skill)
    else:
        print("No skills from the list were found.")

BI
Python
SQL
critical thinking
data analysis
predictive
problem solving
statistics
SQL
Tableau
data analysis
AI
Big Data
Business Intelligence
Cloud
ETL
NoSQL
cloud
spark
AI
SQL
problem solving
BI
SQL
SQL Server
Tableau
business intelligence
data analysis
pipelines
AI
AWS
Azure
Cloud
Data Architecture
Python
R
SQL
Tableau
cloud
AI
BI
Business Intelligence
Power BI
SQL
Tableau
data visualization
BI
IA
Inteligência Artificial
Power BI
SQL
colaboração
qualidade dos dados
BI
Ciência de Dados
Data Science
Power BI
Python
SQL
Spark
análise de dados
visualização de dados
AWS
Airflow
Análise de dados
Azure
BI
GCP
Power BI
Programação
Python
SQL
adaptabilidade
análise de dados
colaboração
computação em nuvem
limpeza de dados
nuvem
visualização de dados
Big Data
ETL
IA
Python
SQL
análise de dados
pipelines
BI
Excel
SQL
data analysis
data visualization
BI
Cloud
Data Storytelling
NumPy
Pandas
Python
SQL
Tableau
análise de dados
ciência de dados
data warehouse
estatística
machine learning
programação
visualização de dados
AI
Data visualization
Excel
artificial intelligence
Machine Learning
Python
R
SQL
critical thinking
data analysis
data cleaning
data science
AWS
Aprendizado de Máquina
Azure
BI
Cloud
ETL
Governança de Dados
IA
Nuvem
Power BI
Programação
Python
R
SQL
Visualização de Dados
análise de dados
aprendizado de máquina
governança de dados
nuvem
programação
BI
Power BI
Python
SQL
Tableau
business intelligence
critical thinking
data science
machine learning
Azure
data analysis
BI
ETL
SQL
cloud
data engineering
data pipeline
data warehouse
Azure
data analysis

In [56]:

# --- Example of processing multiple job posts (assuming they are in a DataFrame) ---
job_description_text = job_descriptions[0:10]

results = {}
for index, row in job_description_text.iterrows():
    job_id = row['job_id']
    text = row['job_description']
    doc = nlp(text)
    matches = matcher(doc)
    skills = set()
    for match_id, start, end in matches:
        skills.add(doc[start:end].text.strip())
    results[job_id] = sorted(list(skills))

print("\n--- Results for multiple jobs ---")
print(results)

--- Results for multiple jobs ---
{4187060561: ['API', 'SQL'], 4142781980: [], 4189553004: [], 4193195407: ['Estatística', 'Excel', 'SQL', 'estatística', 'python', 'trabalho em equipe'], 4175781800: ['Excel', 'Power BI', 'Tableau', 'análise de dados'], 4193413664: ['Power BI'], 4179429367: ['API'], 4184262596: [], 4191196959: ['Aprendizado de Máquina', 'Estatística', 'Python', 'SQL', 'análise de dados', 'cloud computing', 'estatística', 'numpy', 'pandas', 'visualização de dados'], 4188230342: ['Excel', 'MySQL', 'Power BI', 'análise de dados', 'colaboração', 'comunicação eficaz', 'visualização de dados']}

---

In [1]:
from tqdm import tqdm

In [2]:
try:
    nlp = spacy.load("pt_core_news_lg")
    print("Loaded pt_core_news_lg model.")
except OSError:
    print("Model 'pt_core_news_lg' not found. Trying 'pt_core_news_sm'.")
    print("Install larger model with: python -m spacy download pt_core_news_lg")

NameError: name 'spacy' is not defined

In [33]:

# We'll store found skills per row here
skills_per_job = []

for job_description_text in tqdm(job_descriptions[:20]):
    doc = nlp(job_description_text)
    matches = matcher(doc)

    found_skills = set()
    for match_id, start, end in matches:
        span = doc[start:end]
        found_skills.add(span.text.strip().lower())

    skills_per_job.append(list(found_skills))

# Add to your original DataFrame
df = pd.read_csv('../data/raw/jobs_data.csv')
df = df.sample(20)
df['skills_found'] = skills_per_job

100%|██████████| 20/20 [00:01<00:00, 10.36it/s]

In [35]:
df

,job_id,work_model,job_title,company_name,location,time_posted,num_applicants,xp_level,job_type,job_sectors,job_description,skills_found
653,4204988704,Presencial,ANALISTA AMBIENTAL PL BH MG _VG 4295,Arcadis,Belo Horizonte e Região,Há 2 dias,92 candidaturas,Não aplicável,Tempo integral,"Atividades profissionais, científicas e técnicas","Na Arcadis, nosso foco é atrair, reter e desen...","[sql, bi, predictive, data analysis, python, c..."
1245,4206405337,Remoto,Engenheiro de software full stack senior,Netvagas,Brasil,Há 2 dias,NaN,Pleno-sênior,Tempo integral,Fornecimento e gestão de recursos humanos,Sua Missão\nComo Desenvolvedor Full Stack Sêni...,"[tableau, sql, data analysis]"
1118,4153000804,Remoto,Profissional Engenheiro de Visão Computacional...,Luby,Brasil,Há 2 meses,31 candidaturas,Assistente,Tempo integral,Tecnologia da informação e serviços,#VemPraLuby\nAqui Você Terá a Oportunidade De\...,"[spark, etl, big data, cloud, nosql, business ..."
1428,4202290448,Híbrido,Engenheiro de dados senior,Netvagas,"São Paulo, SP",Há 6 dias,NaN,Pleno-sênior,Tempo integral,Fornecimento e gestão de recursos humanos,Você quer fazer parte de uma empresa de tecnol...,"[sql, problem solving, ai]"
1396,4206055435,Híbrido,Engenheiro de Dados Sênior - Dataiku,Niteo Technologies,"São Paulo, Brasil",Há 2 dias,NaN,Pleno-sênior,Outro,Atividades dos serviços de tecnologia da infor...,🔎 Procuramos uma pessoa Engenheira de Dados Sê...,"[tableau, sql, bi, data analysis, business int..."
1051,4205627252,Remoto,Engenheiro(a) de dados Pleno,Confidencial,Brasil,Há 2 dias,94 candidaturas,Assistente,Tempo integral,Fornecimento e gestão de recursos humanos,Estamos a procura de um(a)\nEngenheiro(a) de D...,"[sql, tableau, cloud, python, data architectur..."
2296,4190934080,Híbrido,ANALISTA DE DADOS PLENO,Cogna Educação,"Valinhos, SP",Há 2 semanas,40 candidaturas,Não aplicável,Tempo integral,Atividades de apoio à educação,Somos o grupo educacional mais diversificado d...,"[sql, bi, tableau, data visualization, busines..."
163,4179426946,Remoto,Cientista de Dados - IA & ML,MK Solutions,Brasil,Há 1 mês,84 candidaturas,Assistente,Tempo integral,Desenvolvimento de software,"Conectar o mundo é o que nos move, e conectar ...","[colaboração, sql, bi, power bi, qualidade dos..."
1057,4196438135,Remoto,Engenheiro de Dados Pleno,DBC Company,Brasil,Há 1 semana,46 candidaturas,Pleno-sênior,Tempo integral,Atividades dos serviços de tecnologia da infor...,Quais serão suas responsabilidades?\nFoco em a...,"[spark, sql, bi, análise de dados, data scienc..."
520,4192905718,Presencial,ENGENHEIRO ORÇAMENTISTA PL,Grupo Allonda,"Barueri, SP",Há 2 semanas,NaN,Não aplicável,Contrato,Construção,"Venha fazer parte de um time Pulsante, Ousado ...","[colaboração, gcp, sql, bi, adaptabilidade, ai..."
1501,4194412288,Remoto,Senior Data Scientist,Teramind,Brasil,Há 2 semanas,36 candidaturas,Pleno-sênior,Tempo integral,Atividades de organizações sem fins lucrativos...,"Teramind is a hybrid, global workforce buildin...","[sql, etl, análise de dados, big data, python,..."
730,4168343082,Presencial,COORDENADOR DE OBRAS- Construção Civil,FGR Incorporações SA,"Aparecida de Goiânia, GO",Há 1 mês,192 candidaturas,Não aplicável,Tempo integral,Construção,"Muito mais do que números, a história da FGR é...","[excel, sql, bi, data visualization, data anal..."
2016,4171231072,Presencial,Analista de Dados Pleno,UNIASSELVI,"Indaial, SC",Há 1 mês,NaN,Não aplicável,Tempo integral,Atividades de apoio à educação,Somos a\nVitru Educação\n! 💜\nA maior institui...,"[tableau, machine learning, bi, sql, pandas, a..."
1562,4192198773,Remoto,Data Scientist Senior - Remote | REF#6096,BairesDev,"Salvador, BA",Há 2 semanas,NaN,Pleno-sênior,Tempo integral,Atividades dos serviços de tecnologia da infor...,"At BairesDev®, we've been leading the way in t...","[excel, artificial intelligence, ai, data visu..."
1556,4076239692,Remoto,Senior Data Scientist,Xometry,Brasil,Há 1 semana,158 candidaturas,Pleno-sênior,Tempo integral,Desenvolvimento de software,Xometry (NASDAQ: XMTR) powers the industries o...,"[sql, machine learning, data analysis, data sc..."
2239,4209266627,Presencial,Analista de tecnologia junior v mendes santos co,Netvagas,"Porto Alegre, RS",Há 4 horas,NaN,Assistente,Tempo integral,Fornecimento e gestão de recursos humanos,Estamos em busca de um(a) Analista de Dados pa...,"[sql, etl, bi, análise de dados, aws, cloud, g..."
517,4153187789,Presencial,*ENGENHEIRO ARQUITETO DE DADOS PLENO,QUALIFICAR TI,"São Luis, MA",Há 1 mês,NaN,Não aplicável,Tempo integral,Atividades dos serviços de tecnologia da infor...,"ATIVIDADES\nProjetar, desenvolver e manter pip...","[machine learning, sql, tableau, bi, business ..."
717,4206028218,Presencial,Engenheiro de Planejamento Sr,Obuc Engenharia,"Porto Nacional, TO",Há 2 dias,47 candidaturas,Pleno-sênior,Tempo integral,NaN,"Como\nEngenheiro de Planejamento Sr,\nvocê ser...","[azure, data analysis]"
792,4205993369,Presencial,Engenheiro(a) de Software (Java) | RTB,BTG Pactual,"São Paulo, SP",Há 2 dias,NaN,Pleno-sênior,Tempo integral,Atividades de serviços financeiros,Sobre a área:\nA área é responsável pela plata...,"[sql, etl, bi, cloud, data pipeline, data ware..."
1782,4202591300,Remoto,Data Engineer - Databricks - Senior,Lumenalta,Brasil,Há 6 dias,NaN,Pleno-sênior,Tempo integral,Atividades dos serviços de tecnologia da infor...,Experience Remote done Right. With over 20 yea...,"[azure, data analysis]"

In [34]:
print(df['job_description'].iloc[0])

Na Arcadis, nosso foco é atrair, reter e desenvolver pessoas que compartilhem nossa paixão e compromisso com a melhoria da qualidade de vida. Em troca, oferecemos a você a oportunidade de transformar o seu mundo e o mundo ao seu redor, que poderia ser por meio do trabalho do cliente, aprimorando-se, defendendo a igualdade e a inclusão ou envolvendo-se em trabalhos de caridade, para citar apenas alguns. Nosso pessoal valoriza diferentes perspectivas, se preocupa com a sustentabilidade do nosso planeta e se atreve a moldar o futuro.
Um dos nossos valores fundamentais é ‘as pessoas em primeiro lugar’, e com o apoio de nossa fundação Lovinklaan, investimos em você a longo prazo, para garantir que você alcance seu potencial máximo. Você terá a oportunidade de possuir sua carreira e trabalhar em projetos que definem o setor, encontrando soluções para desafios reais que fazem a diferença na vida das pessoas. Você é incentivado a ter uma mentalidade construtiva e tem espaço para se desenvolver pessoal e profissionalmente, construindo uma carreira flexível que funcione para você.
Descrição da função: ANALISTA AMBIENTAL PLENO MG ENGENHEIRO FLORESTAL OU BIÓLOGO
Responsabilidades da função:
Realizar atividades de campo de Flora para atendimento a PIA, diagnósticos, etc;
Elaboração de PIA, PRADA, diagnocticos de EIA, etc
Qualificações e experiência:
Graduação completa em Biologia ou o Engenharia florestal;
Experiencia na função em atividades como: Inventario florestal, estudos de flora, diagnósticos ambientais de flora;
Inglês intermediário;
CNH B e disponibilidade para viagens.
Por que se tornar um Arcadian?
Nosso trabalho com os clientes tem impacto direto na vida das pessoas e no planeta. Tornamos a mudança, a moradia e o pertencimento às cidades mais seguros, resilientes e sustentáveis. Em parceria com nossos clientes como guardiões responsáveis dos recursos da nossa terra, podemos criar um planeta sustentável.
Continuamos a pensar em novas maneiras de causar impactos positivos e criar melhores experiências para as pessoas; soluções orientadas a dados e digitais tornaram-se parte do DNA da Arcadis. Trabalhando junto com os clientes e usando técnicas como design thinking, podemos chegar ao cerne dos desafios mais urgentes de nossos clientes e trabalhar juntos para resolvê-los.
Como uma empresa global, temos o compromisso de apoiar cinco dos Objetivos de Desenvolvimento Sustentável da ONU para garantir que nossos projetos contribuam para um futuro melhor e mais sustentável para todos. Mas não é apenas o trabalho que fazemos em projetos de clientes que beneficia as comunidades e nosso planeta. Como uma empresa global, temos o compromisso de causar um impacto positivo na sociedade, apoiando as comunidades locais onde operamos.
Para ajudar a proteger nosso planeta, monitoramos e medimos informações não financeiras para informar as decisões de negócios e reduzir nosso próprio impacto ambiental, como parte de nosso compromisso de ter carbono zero líquido como uma empresa global até 2030.
Nosso compromisso com a igualdade, diversidade, inclusão e pertencimento:
Queremos que você seja capaz de trazer o seu melhor para o trabalho todos os dias, por isso levamos a igualdade e a inclusão a sério e nos responsabilizamos por nossas ações. A nossa ambição é ser o empregador de eleição e proporcionar um excelente local de trabalho para todos os nossos colaboradores. Na Arcadis, reconhecemos, respeitamos e valorizamos as diferenças. Por isso, todas as oportunidades são para todos, todas e todes!
Transforme seu mundo

In [27]:
df['skills_found'].iloc[0]

['sql',
 'bi',
 'predictive',
 'data analysis',
 'python',
 'critical thinking',
 'statistics',
 'problem solving']

In [ ]:

# === OPTION A: list of skills in a column (recommended for first analysis)
df.to_csv('../data/processed/jobs_with_skills_list.csv', index=False)

# === OPTION B: One-hot encoding (boolean columns)
for skill in skill_list:
    df[skill] = df['skills_found'].apply(lambda x: skill in x)

df.drop(columns='skills_found', inplace=True)
df.to_csv('../data/processed/jobs_with_skills_flags.csv', index=False)